import { notFound } from "next/navigation";
import { Check, AlertTriangle, Phone, Home } from "lucide-react";
import { getSupabaseAdminClient } from "@/lib/supabase-admin";
import { individualRooms, roomCategories } from "@/lib/rooms-data";
import { Link } from "@/i18n/navigation";
import { siteLinks } from "@/lib/site-config";

export const dynamic = "force-dynamic";

/**
 * Post-payment receipt. The booking id is a UUID generated by Postgres so
 * it's effectively unguessable — anyone with the URL is the guest who just
 * paid. (When Razorpay lands, we can tighten this further by signing the
 * URL with a short-lived token if there's appetite.)
 *
 * Service-role read so we can include guest contact fields if they were
 * collected — the public RLS policy would also let us read this row, but
 * service-role keeps the policy minimal.
 */
export default async function BookingDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  const supabase = getSupabaseAdminClient();
  const { data, error } = await supabase
    .from("room_bookings")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error || !data) notFound();

  const room = individualRooms.find((r) => r.id === data.room_id);
  const variant = room
    ? roomCategories
        .flatMap((c) => c.variants.map((v) => ({ ...v, categoryName: c.name })))
        .find((v) => v.id === room.variantId) ?? null
    : null;

  const status = data.status as
    | "pending"
    | "confirmed"
    | "failed"
    | "cancelled";

  const nights = nightsBetween(data.check_in, data.check_out);
  const total = variant ? variant.pricePerNight * nights : 0;

  return (
    <div
      style={{
        backgroundColor: "#07070d",
        minHeight: "100vh",
        paddingTop: "8rem",
        paddingBottom: "6rem",
      }}
    >
      <div className="max-w-2xl mx-auto px-6 md:px-10">
        {status === "confirmed" && (
          <ConfirmedBlock
            data={data}
            variant={variant}
            roomNumber={room?.roomNumber ?? data.room_id}
            nights={nights}
            total={total}
          />
        )}
        {status === "pending" && <PendingBlock />}
        {(status === "failed" || status === "cancelled") && (
          <FailedBlock status={status} />
        )}
      </div>
    </div>
  );
}

function ConfirmedBlock({
  data,
  variant,
  roomNumber,
  nights,
  total,
}: {
  data: {
    id: string;
    check_in: string;
    check_out: string;
    guest_name: string | null;
    guest_phone: string | null;
    guest_email: string | null;
    provider: string | null;
    provider_payment_id: string | null;
  };
  variant: { name: string; categoryName: string } | null;
  roomNumber: string;
  nights: number;
  total: number;
}) {
  return (
    <>
      <div className="flex items-center gap-3 mb-5">
        <div
          style={{
            width: 44,
            height: 44,
            borderRadius: "50%",
            backgroundColor: "rgba(110,231,183,0.12)",
            border: "1px solid rgba(110,231,183,0.4)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Check size={20} className="text-[#6ee7b7]" />
        </div>
        <div>
          <p
            className="text-white/40"
            style={{
              fontFamily: "'Inter', sans-serif",
              fontSize: "0.7rem",
              letterSpacing: "0.22em",
              textTransform: "uppercase",
              fontWeight: 600,
            }}
          >
            Booking confirmed
          </p>
          <h1
            className="text-white"
            style={{
              fontFamily: "'Playfair Display', serif",
              fontSize: "1.8rem",
              fontWeight: 500,
              lineHeight: 1.2,
            }}
          >
            Thank you for your booking.
          </h1>
        </div>
      </div>

      {data.provider === "demo" && (
        <div
          className="mb-6 flex items-center gap-2"
          style={{
            padding: "8px 12px",
            backgroundColor: "rgba(201,168,76,0.1)",
            border: "1px solid rgba(201,168,76,0.35)",
            fontFamily: "'Inter', sans-serif",
            fontSize: "0.7rem",
            color: "#C9A84C",
            letterSpacing: "0.12em",
            textTransform: "uppercase",
          }}
        >
          <AlertTriangle size={12} />
          Demo booking · no real payment was processed
        </div>
      )}

      <div
        className="p-5 mb-6"
        style={{
          backgroundColor: "#0d0d16",
          border: "1px solid rgba(201,168,76,0.2)",
        }}
      >
        <DetailRow label="Booking ID" value={data.id} mono />
        <DetailRow
          label="Room"
          value={
            variant
              ? `${variant.name} (${variant.categoryName})`
              : `Room ${roomNumber}`
          }
        />
        <DetailRow label="Room number" value={roomNumber} />
        <DetailRow
          label="Check-in"
          value={formatDate(data.check_in)}
        />
        <DetailRow
          label="Check-out"
          value={formatDate(data.check_out)}
        />
        <DetailRow
          label="Nights"
          value={String(nights)}
        />
        {data.guest_name && <DetailRow label="Guest" value={data.guest_name} />}
        {data.guest_phone && <DetailRow label="Phone" value={data.guest_phone} />}
        {data.guest_email && <DetailRow label="Email" value={data.guest_email} />}
        {data.provider_payment_id && (
          <DetailRow label="Payment ref" value={data.provider_payment_id} mono />
        )}

        <div
          style={{
            marginTop: 14,
            paddingTop: 14,
            borderTop: "1px solid rgba(255,255,255,0.06)",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "baseline",
          }}
        >
          <span
            className="text-white"
            style={{
              fontFamily: "'Inter', sans-serif",
              fontSize: "0.9rem",
              fontWeight: 500,
            }}
          >
            Total paid
          </span>
          <span
            style={{
              fontFamily: "'Playfair Display', serif",
              color: "#C9A84C",
              fontSize: "1.6rem",
              fontWeight: 500,
            }}
          >
            ₹{total.toLocaleString("en-IN")}
          </span>
        </div>
      </div>

      <p
        className="text-white/50 mb-6"
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: "0.85rem",
          lineHeight: 1.7,
          fontWeight: 300,
        }}
      >
        Please save this booking ID. Bookings are non-refundable — call the
        resort if you need to discuss anything about your stay.
      </p>

      <div className="flex flex-wrap gap-3">
        <a
          href={siteLinks.tel}
          className="flex items-center gap-2"
          style={{
            fontFamily: "'Inter', sans-serif",
            fontSize: "0.7rem",
            letterSpacing: "0.22em",
            fontWeight: 600,
            textTransform: "uppercase",
            padding: "0.85rem 1.6rem",
            backgroundColor: "#C9A84C",
            color: "#000",
            textDecoration: "none",
          }}
        >
          <Phone size={12} />
          Call the resort
        </a>
        <Link
          href="/"
          className="flex items-center gap-2"
          style={{
            fontFamily: "'Inter', sans-serif",
            fontSize: "0.7rem",
            letterSpacing: "0.22em",
            fontWeight: 600,
            textTransform: "uppercase",
            padding: "0.85rem 1.6rem",
            backgroundColor: "transparent",
            color: "#C9A84C",
            border: "1px solid rgba(201,168,76,0.35)",
            textDecoration: "none",
          }}
        >
          <Home size={12} />
          Back to homepage
        </Link>
      </div>
    </>
  );
}

function PendingBlock() {
  return (
    <div className="text-center">
      <h1
        className="text-white mb-3"
        style={{
          fontFamily: "'Playfair Display', serif",
          fontSize: "1.5rem",
          fontWeight: 500,
        }}
      >
        Booking is being processed
      </h1>
      <p
        className="text-white/55"
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: "0.9rem",
          lineHeight: 1.7,
        }}
      >
        Refresh this page in a moment. If it stays in this state, call the
        resort and we&apos;ll sort it out.
      </p>
    </div>
  );
}

function FailedBlock({ status }: { status: "failed" | "cancelled" }) {
  return (
    <div className="text-center">
      <h1
        className="text-white mb-3"
        style={{
          fontFamily: "'Playfair Display', serif",
          fontSize: "1.5rem",
          fontWeight: 500,
        }}
      >
        {status === "failed"
          ? "Payment did not complete"
          : "Booking was cancelled"}
      </h1>
      <p
        className="text-white/55 mb-6"
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: "0.9rem",
          lineHeight: 1.7,
        }}
      >
        No money has been taken. You can try again from the room page, or
        call the resort directly.
      </p>
      <Link
        href="/hotel"
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: "0.7rem",
          letterSpacing: "0.22em",
          fontWeight: 600,
          textTransform: "uppercase",
          padding: "0.85rem 1.6rem",
          backgroundColor: "#C9A84C",
          color: "#000",
          textDecoration: "none",
        }}
      >
        Back to rooms
      </Link>
    </div>
  );
}

function DetailRow({
  label,
  value,
  mono = false,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div className="flex items-baseline justify-between" style={{ marginBottom: 8 }}>
      <span
        className="text-white/40"
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: "0.68rem",
          letterSpacing: "0.14em",
          textTransform: "uppercase",
          fontWeight: 600,
        }}
      >
        {label}
      </span>
      <span
        className="text-white/85 text-right"
        style={{
          fontFamily: mono
            ? "ui-monospace, monospace"
            : "'Inter', sans-serif",
          fontSize: mono ? "0.75rem" : "0.82rem",
        }}
      >
        {value}
      </span>
    </div>
  );
}

function nightsBetween(start: string, end: string): number {
  const a = new Date(start).getTime();
  const b = new Date(end).getTime();
  return Math.max(1, Math.round((b - a) / 86_400_000));
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}
