/**
 * Single source of truth for client-facing contact details.
 * Values come from NEXT_PUBLIC_* env vars; safe placeholders are used
 * during local development if a variable is missing.
 *
 * To change a value in production, set the env var on the host
 * (Vercel / Netlify / your server) — do NOT edit this file.
 */

export const siteConfig = {
  brand: "Shehnai Resort",

  // Raw phone — used for tel: links. Must include country code and no spaces.
  phone: process.env.NEXT_PUBLIC_PHONE_NUMBER ?? "+919031350700",

  // Pretty-formatted phone — shown to users (footer, contact card).
  phoneDisplay: process.env.NEXT_PUBLIC_PHONE_DISPLAY ?? "+91 90313 50700",

  // WhatsApp number — country code first, no '+', spaces, or dashes.
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? "919031350700",

  email: process.env.NEXT_PUBLIC_EMAIL ?? "info@shehnairesort.com",

  address:
    process.env.NEXT_PUBLIC_ADDRESS ?? "123 Grand Avenue, City",

  social: {
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL ?? "#",
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_URL ?? "#",
    twitter: process.env.NEXT_PUBLIC_TWITTER_URL ?? "#",
  },
} as const;

/** Pre-built href strings for the most common link patterns. */
export const siteLinks = {
  tel: `tel:${siteConfig.phone}`,
  mailto: `mailto:${siteConfig.email}`,
  whatsapp: (message: string) =>
    `https://wa.me/${siteConfig.whatsapp}?text=${encodeURIComponent(message)}`,
};
